# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: math_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12math_service.proto\x12\x0cmath_service\"-\n\x0fMagicAddRequest\x12\x0c\n\x04num1\x18\x01 \x01(\x01\x12\x0c\n\x04num2\x18\x02 \x01(\x01\"\x1f\n\rMagicAddReply\x12\x0e\n\x06result\x18\x01 \x01(\x01\"2\n\x14MagicSubtractRequest\x12\x0c\n\x04num1\x18\x01 \x01(\x01\x12\x0c\n\x04num2\x18\x02 \x01(\x01\"$\n\x12MagicSubtractReply\x12\x0e\n\x06result\x18\x01 \x01(\x01\"?\n\x13MagicFindMinRequest\x12\x0c\n\x04num1\x18\x01 \x01(\x05\x12\x0c\n\x04num2\x18\x02 \x01(\x05\x12\x0c\n\x04num3\x18\x03 \x01(\x05\"#\n\x11MagicFindMinReply\x12\x0e\n\x06result\x18\x01 \x01(\x05\"?\n\x13MagicFindMaxRequest\x12\x0c\n\x04num1\x18\x01 \x01(\x05\x12\x0c\n\x04num2\x18\x02 \x01(\x05\x12\x0c\n\x04num3\x18\x03 \x01(\x05\"#\n\x11MagicFindMaxReply\x12\x0e\n\x06result\x18\x01 \x01(\x05\"\x1a\n\x18GetOperationCountRequest\"\x81\x01\n\x16GetOperationCountReply\x12\x15\n\rmagicAddCount\x18\x01 \x01(\x05\x12\x1a\n\x12magicSubtractCount\x18\x02 \x01(\x05\x12\x19\n\x11magicFindMinCount\x18\x03 \x01(\x05\x12\x19\n\x11magicFindMaxCount\x18\x04 \x01(\x05\x32\xb0\x03\n\x04Math\x12\x46\n\x08magicAdd\x12\x1d.math_service.MagicAddRequest\x1a\x1b.math_service.MagicAddReply\x12U\n\rmagicSubtract\x12\".math_service.MagicSubtractRequest\x1a .math_service.MagicSubtractReply\x12R\n\x0cmagicFindMin\x12!.math_service.MagicFindMinRequest\x1a\x1f.math_service.MagicFindMinReply\x12R\n\x0cmagicFindMax\x12!.math_service.MagicFindMaxRequest\x1a\x1f.math_service.MagicFindMaxReply\x12\x61\n\x11getOperationCount\x12&.math_service.GetOperationCountRequest\x1a$.math_service.GetOperationCountReplyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'math_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MAGICADDREQUEST._serialized_start=36
  _MAGICADDREQUEST._serialized_end=81
  _MAGICADDREPLY._serialized_start=83
  _MAGICADDREPLY._serialized_end=114
  _MAGICSUBTRACTREQUEST._serialized_start=116
  _MAGICSUBTRACTREQUEST._serialized_end=166
  _MAGICSUBTRACTREPLY._serialized_start=168
  _MAGICSUBTRACTREPLY._serialized_end=204
  _MAGICFINDMINREQUEST._serialized_start=206
  _MAGICFINDMINREQUEST._serialized_end=269
  _MAGICFINDMINREPLY._serialized_start=271
  _MAGICFINDMINREPLY._serialized_end=306
  _MAGICFINDMAXREQUEST._serialized_start=308
  _MAGICFINDMAXREQUEST._serialized_end=371
  _MAGICFINDMAXREPLY._serialized_start=373
  _MAGICFINDMAXREPLY._serialized_end=408
  _GETOPERATIONCOUNTREQUEST._serialized_start=410
  _GETOPERATIONCOUNTREQUEST._serialized_end=436
  _GETOPERATIONCOUNTREPLY._serialized_start=439
  _GETOPERATIONCOUNTREPLY._serialized_end=568
  _MATH._serialized_start=571
  _MATH._serialized_end=1003
# @@protoc_insertion_point(module_scope)
